// Code generated by "stringer -type=ObjectType"; DO NOT EDIT.

package types

import "strconv"

const _ObjectType_name = "NilTIntegerTErrorTFunctionTReturnTStringTArrayTBooleanTBuiltinT"

var _ObjectType_index = [...]uint8{0, 4, 12, 18, 27, 34, 41, 47, 55, 63}

func (i ObjectType) String() string {
	if i < 0 || i >= ObjectType(len(_ObjectType_index)-1) {
		return "ObjectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ObjectType_name[_ObjectType_index[i]:_ObjectType_index[i+1]]
}
