// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

const _TokenType_name = "IllegalEOFIdentIntStringNilAssignPlusMinusBangAsteriskSlashCommaSemicolonLParenRParenLBraceRBraceLessThanGreaterThanEqualsNotEqualFunctionLetDeclareAssignTrueFalseIfElseReturnLBracketRBracket"

var _TokenType_index = [...]uint8{0, 7, 10, 15, 18, 24, 27, 33, 37, 42, 46, 54, 59, 64, 73, 79, 85, 91, 97, 105, 116, 122, 130, 138, 141, 154, 158, 163, 165, 169, 175, 183, 191}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
