// Code generated by "stringer -type=Type"; DO NOT EDIT.

package token

import "strconv"

const _Type_name = "IllegalEOFIdentIntStringNilAssignPlusMinusBangAsteriskSlashCommaSemicolonLParenRParenLBraceRBraceLessThanGreaterThanEqualsNotEqualFunctionLetDeclareAssignTrueFalseIfElseReturnLBracketRBracket"

var _Type_index = [...]uint8{0, 7, 10, 15, 18, 24, 27, 33, 37, 42, 46, 54, 59, 64, 73, 79, 85, 91, 97, 105, 116, 122, 130, 138, 141, 154, 158, 163, 165, 169, 175, 183, 191}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
