// Code generated by "stringer -type=Opcode"; DO NOT EDIT.

package opcode

import "strconv"

const _Opcode_name = "ConstPopAddSubMulDivNotNeg"

var _Opcode_index = [...]uint8{0, 5, 8, 11, 14, 17, 20, 23, 26}

func (i Opcode) String() string {
	if i >= Opcode(len(_Opcode_index)-1) {
		return "Opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Opcode_name[_Opcode_index[i]:_Opcode_index[i+1]]
}
